import type { ContextFreeGrammar, FailureReason } from "@/types/cfg";

// ─── Helpers ─────────────────────────────────────────────────────────────

/** Check whether the grammar has any recursive cycle with no base terminal case */
function hasInfiniteLoop(grammar: ContextFreeGrammar): boolean {
  // A non-terminal is "productive" if it can derive a purely terminal string.
  // We compute the set of productive NTs via a fixpoint.
  const productive = new Set<string>();
  let changed = true;

  while (changed) {
    changed = false;
    for (const prod of grammar.productions) {
      if (productive.has(prod.lhs)) continue;
      const rhs = prod.rhs;
      // Epsilon production → always productive
      if (rhs.length === 0) {
        productive.add(prod.lhs);
        changed = true;
        continue;
      }
      // All RHS symbols must be productive or terminal
      const allGood = rhs.every(
        (sym) => grammar.terminals.has(sym) || productive.has(sym)
      );
      if (allGood) {
        productive.add(prod.lhs);
        changed = true;
      }
    }
  }

  return !productive.has(grammar.startSymbol);
}

/** Estimate the language the grammar generates (for diagnostics) */
function estimateLanguagePattern(grammar: ContextFreeGrammar): string {
  const terminals = [...grammar.terminals];
  const prods = grammar.productions;

  // Check for balanced pair pattern
  const hasEpsilon = prods.some((p) => p.lhs === grammar.startSymbol && p.rhs.length === 0);
  const hasSelfEmbedding = prods.some(
    (p) =>
      p.lhs === grammar.startSymbol &&
      p.rhs.length >= 3 &&
      p.rhs[0] !== grammar.startSymbol &&
      p.rhs[p.rhs.length - 1] !== grammar.startSymbol &&
      p.rhs.includes(grammar.startSymbol)
  );

  if (hasEpsilon && hasSelfEmbedding && terminals.length >= 2) {
    const [a, b] = terminals;
    return `strings of the form ${a}ⁿ${b}ⁿ (balanced pairs)`;
  }

  // Check for "repeated single terminal" pattern
  if (terminals.length === 1) {
    const [t] = terminals;
    return `strings consisting solely of "${t}"s`;
  }

  // Arithmetic-like
  if (terminals.some((t) => ["+", "*", "(", ")"].includes(t))) {
    return "arithmetic expressions";
  }

  return "a specific context-free language";
}

/** Return characters in target that are not in grammar terminals */
function getMissingTerminals(
  grammar: ContextFreeGrammar,
  target: string
): string[] {
  return [...new Set([...target].filter((c) => !grammar.terminals.has(c)))];
}

// ─── Main analyzeFailure ──────────────────────────────────────────────────

export function analyzeFailure(
  grammar: ContextFreeGrammar,
  target: string
): FailureReason {
  // 1. Missing terminals
  const missing = getMissingTerminals(grammar, target);
  if (missing.length > 0) {
    const available = [...grammar.terminals].join(", ");
    return {
      type: "missing_terminals",
      message: `The character(s) "${missing.join('", "')}" do not appear in this grammar's terminal set.`,
      suggestion: `The grammar only recognises: ${available || "(none)"}. Please use only those characters in your input.`,
      missing,
    };
  }

  // 2. Infinite loop (no terminal derivation possible at all)
  if (hasInfiniteLoop(grammar)) {
    return {
      type: "infinite_loop",
      message: `The grammar contains recursive rules with no base case — it can never produce a terminal string.`,
      suggestion: `Add a base-case production that terminates the recursion (e.g., "${grammar.startSymbol} → a" or "${grammar.startSymbol} → ε").`,
    };
  }

  // 3. No derivation path found (valid grammar, but string not in language)
  const pattern = estimateLanguagePattern(grammar);
  const termList = [...grammar.terminals].join("");
  const hasEpsilon = grammar.productions.some(
    (p) => p.lhs === grammar.startSymbol && p.rhs.length === 0
  );

  // Build a more detailed diagnostic
  const examples: string[] = [];
  if (hasEpsilon) examples.push("ε (empty string)");
  if (termList.length > 0) {
    const t = termList[0];
    examples.push(`"${t}"`, `"${t}${t}"`, `"${t}${t}${t}"`);
  }

  const exampleStr =
    examples.length > 0
      ? `Some strings that might work: ${examples.slice(0, 3).join(", ")}.`
      : "";

  return {
    type: "no_derivation_path",
    message: `"${target}" is not in the language generated by this grammar. The grammar produces ${pattern}.`,
    suggestion: `${exampleStr} Try a string that matches the grammar's pattern, or modify the grammar to include this string.`,
  };
}
